version: '2'
services:
  api:
    build: .
    container_name: api
    image: ollebo/api
    volumes:
      - ./code:/code
    ports:
      - 8080:8080
    environment:
      - ES=http://elasticsearch:9200
      - MONGO=mongodb://mongo:27017
      - NATS=nats://nats:4222
      - KAFKA=redpanda-0.redpanda:9093,redpanda-1.redpanda:9093,redpanda-2.redpanda:9093

    networks:
      - ollebo
networks:
  ollebo:
    external: true
