version: '2'
services:
  api:
    build: .
    image: hrb/api
    volumes:
      - ./:/code
    command: tail -f /etc/fstab
    ports:
      - 8088:8080
    environment:
      - REDISHOST=redis
      - REDISPORT=6379
      - AUTH_TOKENS=['1234','6789']
      - ELASTICSEARCH=elasticsearch
      - ES_INDEX=elasticsearch
      - INDB=influxdb
      - INDB_PORT=8086
      - INDB_USER=influxdb
      - INDB_PASSWORD=influxdb
      - INDB_DATABASE=ollebo
      - INDB_TOKEN=yduilsJKTS576576ASD
      - INDB_ORG=ollebo
  #zero:
  #  image: dgraph/dgraph:latest
  #  ports:
  #    - 5080:5080
  #    - 6080:6080
  #  restart: on-failure
  #  command: dgraph zero --my=zero:5080
  #  volumes:
  #    - ./dgraph/zero:/datan
  #alpha:
  #  image: dgraph/dgraph:latest
  #  volumes:
  #    - ./dgraph/alpha:/datan
  #  ports:
  #    - 8080:8080
  #    - 9080:9080
  #  restart: on-failure
  #  command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --whitelist=172.17.0.0:172.25.0.0,192.168.0.0:192.168.225.0 
  #ratel:
  #  image: dgraph/dgraph:latest
  #  ports:
  #    - 8000:8000
  #  command: dgraph-ratel
      
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  

