version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    image: ollebo/api
    #command: tail -f /etc/fstab
    volumes:
      - ./:/data
    ports:
      - 8888:8080
    environment:
      - ES=http://elasticsearch:9200
      - MONGOURL=mongodb://admin:admin123@mongo1:27017/ollebo?authSource=admin
      - NATS=nats://nats:4222
      - POSTGRES_DB=ollebo
      - POSTGRES_HOST=dw-server-postgres
      - POSTGRES_PASSWORD=ollebo
      - POSTGRES_USER=ollebo
      - LOCALSTACK=true
      - MAPS_SQS=https://localhost.localstack.cloud:4566/000000000000/maps
      - EVENT_SQL=https://localhost.localstack.cloud:4566/000000000000/events
      - LOCALSTACK_ENDPOINT=http://192.168.1.130:4566
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - AWS_LAMBDA_RUNTIME_API=python3.8


 
    networks:
      - dw-net
    #command: tail -f /etc/fstab
    #depends_on:
    #  - database

#  database:
#    image: postgis/postgis
#    container_name: postgis
#    volumes:
#      - ./data:/data/db
#    ports:
#      - 27017:27017
#    environment:
#      - POSTGRES_PASSWORD=ollebo
#      - POSTGRES_USER=ollebo
#      - POSTGRES_DB=ollebo
#    networks:
#      - mantiser
networks:
  mantiser:
    external: true
  dw-net:
    driver: bridge
    name: dw-net
    external: true
