version: '2'
services:
  api:
    build: .
    volumes:
      - ./code:/code2
    ports:
      - 8080:8080
    environment:
      - ES=http://elasticsearch:9200
      - MONGO=mongodb://mongo:27017
      - NATS=nats://nats:4222
    networks:
      - ollebo
networks:
  ollebo:
    external: true
