version: '2'
services:
  api:
    build: .
    container_name: api
    image: ollebo/api
    volumes:
      - ./code:/code
    ports:
      - 8888:8080
    environment:
      - ES=http://elasticsearch:9200
      - MONGOURL=mongodb://admin:admin123@mongo1:27017/ollebo?authSource=admin
      - NATS=nats://nats:4222
 
    networks:
      - mantiser
    command: tail -f /etc/fstab
networks:
  mantiser:
    external: true

