version: '2'
services:
  api:
    build: .
    container_name: api
    image: ollebo/api
    volumes:
      - ./code:/code
    ports:
      - 8080:8080
    environment:
      - ES=http://elasticsearch:9200
      - MONGO=mongodb://mongo:27017
      - NATS=nats://nats:4222
      - KAFKA=redpanda:9092
      - KAFKA_TLS=none

    networks:
      - ollebo
    command: tail -f /etc/fstab
networks:
  ollebo:
    external: true
