version: '2'
services:
  api:
    build: .
    container_name: api
    image: ollebo/api
    volumes:
      - ./code:/code
    ports:
      - 8080:8080
    environment:
      - ES=http://elasticsearch:9200
      - MONGO=mongodb://mongo:27017
      - NATS=nats://nats:4222
      - KAFKA=redpanda-external.redpanda.svc.cluster.local:9094

    networks:
      - ollebo
networks:
  ollebo:
    external: true
