
kind: Secret
type: Opaque
apiVersion: v1
stringData:
  mongouri: ""
metadata:
  name: ollebo-app-demo
  namespace: ollebo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ollebo-api
  template:
    metadata:
      labels:
        app: ollebo-api
    spec:
      containers:
        - command:
          - tail
          - -f
          - /dev/null
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: core-app
                key: password
          - name: REDISHOST
            value: redis
          - name: REDIS
            value: redis
          - name: REDISPORT
            value: "6379"
          - name: NATS
            value: nats://nats:4222
          - name: POSTGRES_DB
            value: maps
          - name: POSTGRES_HOST
            value: core-rw
          - name: POSTGRES_USER
            value: ollebo        
          - name: PROJECT
            value: ollebo
          image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: events
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
        - image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
          name: api
          imagePullPolicy: Always
          env:
          - name: REDISHOST
            value: redis
          - name: REDIS
            value: redis
          - name: REDISPORT
            value: "6379"
          - name: NATS
            value: nats://nats:4222
          - name: POSTGRES_DB
            value: maps
          - name: POSTGRES_HOST
            value: database
          - name: POSTGRES_PASSWORD
            value: ollebo
          - name: POSTGRES_USER
            value: ollebo           
          - name: PROJECT
            value: ollebo
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ollebo-api
  name: api
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.ollebo.com
spec:
  ports:
  - name: api
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ollebo-api
  sessionAffinity: None
  type: ClusterIP