apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ollebo-api
  template:
    metadata:
      labels:
        app: ollebo-api
    spec:
      volumes:
        - name: tls
          secret:
            secretName: redpanda-default-cert
      containers:
        - command:
          - python3
          - /code/events/consumeEvents.py
          env:
          - name: REDISHOST
            value: redis
          - name: REDIS
            value: redis
          - name: REDISPORT
            value: "6379"
          - name: ELASTICSEARCH
            value: http://elasticsearch:9200
          - name: ES_INDEX
            value: ollebo
          - name: MEILISEARCH
            value: http://meilisearch:7700
          - name:  KAFKA_TLS
            value: "SSL"
          - name: KAFKA
            value: redpanda-0.redpanda.ollebo.svc.cluster.local.:9093,redpanda-1.redpanda.ollebo.svc.cluster.local.:9093,redpanda-2.redpanda.ollebo.svc.cluster.local.:9093
          - name: MEILISEARCH_KEY
            valueFrom:
              secretKeyRef:
                key: MEILI_MASTER_KEY
                name: meilisearch-master-key
          - name: MONGOURL
            valueFrom:
              secretKeyRef:
                key: connectionString.standard
                name: mongodb-cluster-ollebo-mongouser
          - name: PROJECT
            value: ollebo
          image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: events
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
          - mountPath: /tls/
            name: tls
            readOnly: true
        - image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
          name: api
          imagePullPolicy: Always
          env:
            - name: REDISHOST
              value: redis
            - name: REDIS
              value: redis
            - name: REDISPORT
              value: "6379"
            - name: AUTH_TOKENS
              value: "['1234','6789']"
            - name: ELASTICSEARCH
              value: http://elasticsearch:9200
            - name: ES_INDEX
              value: ollebo
            - name:  MEILISEARCH
              value: http://meilisearch:7700
            - name:  KAFKA_TLS
              value: "SSL"
            - name:  KAFKA
              value: redpanda-0.redpanda.ollebo.svc.cluster.local.:9093,redpanda-1.redpanda.ollebo.svc.cluster.local.:9093,redpanda-2.redpanda.ollebo.svc.cluster.local.:9093
            - name:  MEILISEARCH_KEY
              valueFrom:
                secretKeyRef:
                  name: meilisearch-master-key
                  key: MEILI_MASTER_KEY
            - name:  MONGOURL
              valueFrom:
                secretKeyRef:
                  name: mongodb-cluster-ollebo-mongouser
                  key: connectionString.standard
            - name: PROJECT
              value: ollebo
          volumeMounts:
            - name: tls
              readOnly: true
              mountPath: "/tls/"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ollebo-api
  name: api
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.ollebo.com
spec:
  ports:
  - name: api
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ollebo-api
  sessionAffinity: None
  type: ClusterIP