name: Docker Image CI
env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
on:
  push:
    branches: [ "master","main" ]
  pull_request:
    branches: [ "master","main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Check out Manifest
        uses: actions/checkout@master
        with:
          repository: Ollebo/manifests
          path: manifest
          ssh-key: ${{ secrets.SAM_SSH }}
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: | 
            helm template chart/  >> manifest/test-file.yaml
            cat manifest/test-file.yaml
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          directory: manifest
          branch: master
          github_token: ${{ secrets.TOKEN_GITHUB }}
      - name: "Call API"
        uses: indiesdev/curl@v1.1
        with:
          url: https://hooks.slack.com/services/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
          method: "POST"
          accept: 200,201,204
          headers: 'Content-type: application/json'
          body: '{"text":"Project ${{ env.IMAGE_NAME }} is now build and pushed, Will be deployed"}'

      
